<?php

namespace App\Enums\Config;

enum ConfigName: string
{
    case CLIENT_ID_APP = "CLIENT_ID_APP";

    case API_KEY = "API_KEY";

    case CHECKSUM_KEY = "CHECKSUM_KEY";

    case COIN_POST_PRODUCT_SALE = "COIN_POST_PRODUCT_SALE";

    case COIN_POST_PRODUCT_AUCTION = "COIN_POST_PRODUCT_AUCTION";

    case PRICE_ONE_COIN = "PRICE_ONE_COIN";

    case COIN_BIND_PRODUCT_AUCTION = "COIN_BIND_PRODUCT_AUCTION";

    case TIME_DELAY_AUCTION_BIND = "TIME_DELAY_AUCTION_BIND";

    case MARQUEE_CONTENT = "MARQUEE_CONTENT";

    case DISPLAY_TIME_AFTER_AUCTION = "DISPLAY_TIME_AFTER_AUCTION";
}
