<?php

namespace App\Enums\Config;

enum ConfigName: string
{
    case ADMIN_ACCOUNT_BANK_BIN = "ADMIN_ACCOUNT_BANK_BIN";

    case ADMIN_ACCOUNT_BANK_NAME = "ADMIN_ACCOUNT_BANK_NAME";

    case ADMIN_ACCOUNT_BANK_ACCOUNT = "ADMIN_ACCOUNT_BANK_ACCOUNT";

    case COIN_POST_PRODUCT_SALE = "COIN_POST_PRODUCT_SALE";

    case COIN_POST_PRODUCT_AUCTION = "COIN_POST_PRODUCT_AUCTION";

    case PRICE_ONE_COIN = "PRICE_ONE_COIN";


}
